# Setup
title:               River City Social
tagline:             'Touch Grass'
description:         'Grassroots local event sharing'
url:                 http://rivercitysocial.org
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              N8 T
  url:               https://natetreme.com
  email:             nathantreme@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
